### ISSUE TITLE
Add intents.

### ISSUE THREAD

**Issue by vext01** [carlosrafaelgn/FPlayAndroid#11]
Hi again,

I notice that music and playlist files are not registered to play under fplay on my system. I.e. when I choose a mp3, ogg, pls, m3u... using the cyanogenmod file browser, under the open with menu fplay is not listed.

This is kind of a rare use case, but it is useful on websites like soma.fm where you are given a pls file, which android just dumps in the Download directory. It would be neat if when clicking the file (or the notification that the file has finished downloading), that the file either opened in fplay or the menu appears asking which app to open in, fplay being an option.

I don't know much about Android development (I've written a total of zero lines of android code to date), but I think you just need to register an intent?

Thanks

**Comment by Soudain** [comment]
Hi Carlos,

I don't know if you have some time to work on FPlay anymore, but if you have, I will really appreciate the same thing vext01 asked for : being able to make FPlay the default player !

Another thing : if you want a french translator, I may help you with pleasure !

Thank you.

**Comment by carlosrafaelgn** [comment]
Hi Soudain!

Sorry for the delay :cry: I have not received this message in my e-mail, and therefore, I failed to reply to you on time.

Well... As you can see, I already added that feature in version 1.42 :wink: 

As for the French translation..... Fantastic!!!! Your help will be really welcome :smile: 

Drop me an email!!!

Regards!!!
