### ISSUE TITLE
Album Art

### ISSUE THREAD

**Issue by vext01** [carlosrafaelgn/FPlayAndroid#13]
Hi,

Is there anywhere in the interface that we would like to show artwork (if existing)?

It could be as simple as displaying cover.jpg in the same folder, or if not existing, the first image file found in the folder.

Cheers

**Comment by hasturhub** [comment]
Hello Carlos I'm a great fan of your app, it is probably the one on my phone I most enjoy! Many try to do too much in their functionality and interface and so this project is very refreshing. But I also miss album art. Sometimes when I look for a particular song or album I like to see a familiar cover while I listen. Maybe there could be a visualizer that displayed the embedded cover under the song? I don't know if that's feasible though.

OK thanks 4 your hard work

**Comment by carlosrafaelgn** [comment]
Hi, there!!!

Thanks for the words! I'm super happy to know you like the player :)

Yes, that would be really cool. Suggestion noted!

I'm about to upload a new version to the Play Store, with improvements for
the Particles visualizer. As your suggestion is not very complex to
implement, expect to see it soon ;)

Best regards!
