### ISSUE TITLE
Number of albums and files in "Artist" view

### ISSUE THREAD

**Issue by cocofifi** [carlosrafaelgn/FPlayAndroid#14]
Since my previous request was implemented very quickly and with great effect, I felt encouraged to contribute another idea to the development of the fantastic FPlay. While I'm a devout user of FPlay, I look around from time to time to see how other players behave and yesterday I tested a player made by a company that produces various audio equipment, Onkyo, and their HF Player (https://play.google.com/store/apps/details?id=com.onkyo.jp.musicplayer&hl=en). A useful feature of their music browser is the presence of two numbers for each artist: number of albums and total number of songs by the artist. Having these numbers is very useful to differentiate the artists for which I have individual albums from ones for which I have only one or two songs, generally in compilations.

So instead of having just:
<pre>
Harry Nisson                           [  ]
Jennifer Clarke                        [  ]
etc
</pre>

It would be great to have something like:
<pre>
Harry Nilsson   2 Albums / 34 songs     [  ]
Jennifer Clarke 1 Album / 2 songs       [  ]
</pre>

The size and position of the annotations are a matter of debate. The app I mentioned will write 1 Album, even if it's just one independent song - this is the default. Maybe the better solution would be:
<pre>
Harry Nilsson   2 Albums / 34 songs     [  ]
Jennifer Clarke           2 songs       [  ]
</pre>

In an ideal word, FPlay would even let the user sort the list by number of songs per artist ... Thus, the artist for which we have most songs would be at the top of the list.

Thank you for the great work done on FPlay. Best,

Cosmin

Edit: this interface change could also apply to the Albums view (many of the songs I have come from an album but I only have one song on the phone). Knowing if there are more or not is useful.

**Comment by carlosrafaelgn** [comment]
Hi Cosmin!

Thanks! This could be really useful, indeed!

I will run a few tests to see if this will not have a deep impact in performance/memory, and depending on the results this could be implemented in the app.

As soon as I have news, I will let you in :)

Regards!

**Comment by carlosrafaelgn** [comment]
Hi again, Cosmin!

Indeed it wasn't such a difficult request :)

I submitted version 1.37 to the Play Store this morning. Tomorrow I will submit version 1.38 with this new feature you just asked, after running a few more tests today...

Best regards!

**Comment by cocofifi** [comment]
Wow - that's fantastic! Thank you very much! All the best,

Cosmin

**Comment by carlosrafaelgn** [comment]
You are welcome! I'm glad to know you liked it! :smile:

Thanks!!!
